a = int(input('Digite o primeiro numero: '))
b = int(input('Digite o segundo numero: '))
print(a, b)
print("A soma eh: ", a + b)
print("A subtracao eh: ", a - b)
print("A divisao eh: ", a / b)
print("A multiplicacao eh: ", a * b)
print("O resto da divisao eh: ", a % b)
